/*
 TechBlog SQL Export

 Source Server         : localhost:3307
 Source Schema         : techblogdb
 Generated By          : Codex repair script
 File Encoding         : UTF-8

 Date: 2026-04-10
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for attachments
-- ----------------------------
DROP TABLE IF EXISTS `attachments`;
CREATE TABLE `attachments` (
  `AttachmentID` int NOT NULL AUTO_INCREMENT COMMENT '附件ID',
  `PostID` int DEFAULT NULL COMMENT '关联文章（可为空，表示临时附件）',
  `UserID` int NOT NULL COMMENT '上传者',
  `OriginalName` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '原始文件名',
  `StoredName` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '存储文件名',
  `MimeType` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '文件类型',
  `StoragePath` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '物理存储路径，相对/绝对',
  `FileSize` int NOT NULL COMMENT '文件大小(字节)',
  `UploadedAt` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '上传时间',
  `IsTemporary` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否临时（未最终关联文章）',
  `TempKey` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '编辑会话键（用于 Draft 期归属）',
  `Description` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '文件描述',
  `RefCount` int NOT NULL DEFAULT '0' COMMENT '引用计数（当前文章内容中引用次数）',
  `IsDeleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '软删除标记',
  `DeletedAt` timestamp NULL DEFAULT NULL COMMENT '软删除时间',
  `FileHash` char(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `IsExternal` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否外链',
  `ExternalURL` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '外链原始地址',
  PRIMARY KEY (`AttachmentID`) USING BTREE,
  UNIQUE KEY `StoredName` (`StoredName`) USING BTREE,
  UNIQUE KEY `UK_Attachments_PostID_FileHash` (`PostID`,`FileHash`) USING BTREE,
  KEY `FK_Attachments_Users` (`UserID`) USING BTREE,
  KEY `IDX_Attachments_FileHash` (`FileHash`) USING BTREE,
  KEY `IDX_Attachments_TempKey` (`TempKey`) USING BTREE,
  KEY `IDX_Attachments_IsTemporary` (`IsTemporary`) USING BTREE,
  CONSTRAINT `FK_Attachments_Posts` FOREIGN KEY (`PostID`) REFERENCES `posts` (`PostID`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `FK_Attachments_Users` FOREIGN KEY (`UserID`) REFERENCES `users` (`UserID`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=61 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='文件附件表';

-- ----------------------------
-- Table structure for categories
-- ----------------------------
DROP TABLE IF EXISTS `categories`;
CREATE TABLE `categories` (
  `CategoryID` int NOT NULL AUTO_INCREMENT COMMENT '分类ID',
  `Name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '分类名称',
  `Description` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '分类描述',
  `ParentCategoryID` int DEFAULT NULL COMMENT '父分类ID',
  `CreatedBy` int NOT NULL COMMENT '创建者',
  `CreatedAt` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UpdatedAt` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`CategoryID`) USING BTREE,
  UNIQUE KEY `Name` (`Name`) USING BTREE,
  KEY `FK_Categories_Self` (`ParentCategoryID`) USING BTREE,
  KEY `FK_Categories_Users` (`CreatedBy`) USING BTREE,
  CONSTRAINT `FK_Categories_Self` FOREIGN KEY (`ParentCategoryID`) REFERENCES `categories` (`CategoryID`) ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT `FK_Categories_Users` FOREIGN KEY (`CreatedBy`) REFERENCES `users` (`UserID`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='文章分类表';

-- ----------------------------
-- Table structure for comments
-- ----------------------------
DROP TABLE IF EXISTS `comments`;
CREATE TABLE `comments` (
  `CommentID` int NOT NULL AUTO_INCREMENT COMMENT '评论ID',
  `PostID` int NOT NULL COMMENT '文章ID',
  `UserID` int DEFAULT NULL COMMENT '用户ID',
  `ParentCommentID` int DEFAULT NULL COMMENT '父评论ID',
  `Content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '评论内容',
  `Status` enum('approved','pending','spam') CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'approved' COMMENT '审核状态',
  `CreatedAt` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LastEditedAt` timestamp NULL DEFAULT NULL COMMENT '编辑时间',
  `CanDelete` tinyint(1) DEFAULT '1' COMMENT '用户是否可删除',
  PRIMARY KEY (`CommentID`) USING BTREE,
  KEY `FK_Comments_Posts` (`PostID`) USING BTREE,
  KEY `FK_Comments_Users` (`UserID`) USING BTREE,
  KEY `FK_Comments_Parent` (`ParentCommentID`) USING BTREE,
  CONSTRAINT `FK_Comments_Parent` FOREIGN KEY (`ParentCommentID`) REFERENCES `comments` (`CommentID`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `FK_Comments_Posts` FOREIGN KEY (`PostID`) REFERENCES `posts` (`PostID`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `FK_Comments_Users` FOREIGN KEY (`UserID`) REFERENCES `users` (`UserID`) ON DELETE SET NULL ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=42 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='文章评论表';

-- ----------------------------
-- Table structure for operationlogs
-- ----------------------------
DROP TABLE IF EXISTS `operationlogs`;
CREATE TABLE `operationlogs` (
  `LogID` int NOT NULL AUTO_INCREMENT COMMENT '日志ID',
  `UserID` int DEFAULT NULL COMMENT '操作用户ID',
  `OperationType` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '操作类型',
  `TargetType` enum('post','comment','user','category','tag','revision') CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '操作对象类型',
  `TargetID` int DEFAULT NULL COMMENT '操作对象ID',
  `Details` json DEFAULT NULL COMMENT '操作详情',
  `IPAddress` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '操作IP',
  `UserAgent` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '浏览器标识',
  `Timestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
  PRIMARY KEY (`LogID`) USING BTREE,
  KEY `FK_Logs_Users` (`UserID`) USING BTREE,
  CONSTRAINT `FK_Logs_Users` FOREIGN KEY (`UserID`) REFERENCES `users` (`UserID`) ON DELETE SET NULL ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=191 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='系统操作日志';

-- ----------------------------
-- Table structure for postcategories
-- ----------------------------
DROP TABLE IF EXISTS `postcategories`;
CREATE TABLE `postcategories` (
  `PostID` int NOT NULL COMMENT '文章ID',
  `CategoryID` int NOT NULL COMMENT '分类ID',
  PRIMARY KEY (`PostID`,`CategoryID`) USING BTREE,
  KEY `FK_PostCategories_Categories` (`CategoryID`) USING BTREE,
  CONSTRAINT `FK_PostCategories_Categories` FOREIGN KEY (`CategoryID`) REFERENCES `categories` (`CategoryID`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `FK_PostCategories_Posts` FOREIGN KEY (`PostID`) REFERENCES `posts` (`PostID`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='文章分类关系表';

-- ----------------------------
-- Table structure for postfavorites
-- ----------------------------
DROP TABLE IF EXISTS `postfavorites`;
CREATE TABLE `postfavorites` (
  `PostID` int NOT NULL,
  `UserID` int NOT NULL,
  `CreatedAt` datetime NOT NULL,
  PRIMARY KEY (`PostID`,`UserID`),
  UNIQUE KEY `postfavorites_UserID_PostID_unique` (`PostID`,`UserID`),
  KEY `UserID` (`UserID`),
  CONSTRAINT `postfavorites_ibfk_1` FOREIGN KEY (`PostID`) REFERENCES `posts` (`PostID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `postfavorites_ibfk_2` FOREIGN KEY (`UserID`) REFERENCES `users` (`UserID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----------------------------
-- Table structure for postlikes
-- ----------------------------
DROP TABLE IF EXISTS `postlikes`;
CREATE TABLE `postlikes` (
  `PostID` int NOT NULL,
  `UserID` int NOT NULL,
  `CreatedAt` datetime NOT NULL,
  PRIMARY KEY (`PostID`,`UserID`),
  UNIQUE KEY `postlikes_UserID_PostID_unique` (`PostID`,`UserID`),
  KEY `UserID` (`UserID`),
  CONSTRAINT `postlikes_ibfk_1` FOREIGN KEY (`PostID`) REFERENCES `posts` (`PostID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `postlikes_ibfk_2` FOREIGN KEY (`UserID`) REFERENCES `users` (`UserID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----------------------------
-- Table structure for postrevisions
-- ----------------------------
DROP TABLE IF EXISTS `postrevisions`;
CREATE TABLE `postrevisions` (
  `RevisionID` int NOT NULL AUTO_INCREMENT COMMENT '修订版本ID',
  `PostID` int NOT NULL COMMENT '关联文章ID',
  `UserID` int NOT NULL COMMENT '修改者ID',
  `Title` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '修订标题',
  `Content` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '修订内容',
  `Excerpt` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '修订摘要',
  `RevisionNotes` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '修订说明',
  `CreatedAt` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修订时间',
  `RevisionType` enum('initial','update','rollback') CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'update' COMMENT '修订类型',
  PRIMARY KEY (`RevisionID`) USING BTREE,
  KEY `FK_Revisions_Posts` (`PostID`) USING BTREE,
  KEY `FK_Revisions_Users` (`UserID`) USING BTREE,
  CONSTRAINT `FK_Revisions_Posts` FOREIGN KEY (`PostID`) REFERENCES `posts` (`PostID`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `FK_Revisions_Users` FOREIGN KEY (`UserID`) REFERENCES `users` (`UserID`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=107 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='文章修订历史';

-- ----------------------------
-- Table structure for posts
-- ----------------------------
DROP TABLE IF EXISTS `posts`;
CREATE TABLE `posts` (
  `PostID` int NOT NULL AUTO_INCREMENT COMMENT '文章唯一标识',
  `UserID` int NOT NULL COMMENT '作者ID',
  `Title` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '文章标题',
  `Slug` varchar(220) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'URL友好标识',
  `Content` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '文章内容',
  `Excerpt` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '文章摘要',
  `Status` enum('draft','published','archived') CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'draft' COMMENT '文章状态',
  `CreatedAt` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UpdatedAt` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `PublishedAt` timestamp NULL DEFAULT NULL COMMENT '发布时间',
  `ViewCount` int DEFAULT '0' COMMENT '浏览次数',
  `FeaturedImageURL` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '封面图URL',
  `CurrentRevisionID` int DEFAULT NULL COMMENT '当前生效的修订版本',
  PRIMARY KEY (`PostID`) USING BTREE,
  UNIQUE KEY `Slug` (`Slug`) USING BTREE,
  KEY `FK_Posts_Users` (`UserID`) USING BTREE,
  KEY `idx_posts_status_publishedat` (`Status`,`PublishedAt`) USING BTREE,
  FULLTEXT KEY `ft_posts_title_excerpt_content` (`Title`,`Excerpt`,`Content`),
  CONSTRAINT `FK_Posts_Users` FOREIGN KEY (`UserID`) REFERENCES `users` (`UserID`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=63 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='博客文章表';

-- ----------------------------
-- Table structure for posttags
-- ----------------------------
DROP TABLE IF EXISTS `posttags`;
CREATE TABLE `posttags` (
  `PostID` int NOT NULL COMMENT '文章ID',
  `TagID` int NOT NULL COMMENT '标签ID',
  PRIMARY KEY (`PostID`,`TagID`) USING BTREE,
  KEY `FK_PostTags_Tags` (`TagID`) USING BTREE,
  CONSTRAINT `FK_PostTags_Posts` FOREIGN KEY (`PostID`) REFERENCES `posts` (`PostID`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `FK_PostTags_Tags` FOREIGN KEY (`TagID`) REFERENCES `tags` (`TagID`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='文章标签关系表';

-- ----------------------------
-- Table structure for roles
-- ----------------------------
DROP TABLE IF EXISTS `roles`;
CREATE TABLE `roles` (
  `RoleID` int NOT NULL AUTO_INCREMENT,
  `Name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `Description` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`RoleID`) USING BTREE,
  UNIQUE KEY `Name` (`Name`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

-- ----------------------------
-- Table structure for tags
-- ----------------------------
DROP TABLE IF EXISTS `tags`;
CREATE TABLE `tags` (
  `TagID` int NOT NULL AUTO_INCREMENT COMMENT '标签ID',
  `Name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '标签名称',
  `Description` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '标签描述',
  `CreatedBy` int NOT NULL COMMENT '创建者',
  `CreatedAt` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`TagID`) USING BTREE,
  UNIQUE KEY `Name` (`Name`) USING BTREE,
  KEY `FK_Tags_Users` (`CreatedBy`) USING BTREE,
  CONSTRAINT `FK_Tags_Users` FOREIGN KEY (`CreatedBy`) REFERENCES `users` (`UserID`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='文章标签表';

-- ----------------------------
-- Table structure for userroles
-- ----------------------------
DROP TABLE IF EXISTS `userroles`;
CREATE TABLE `userroles` (
  `UserID` int NOT NULL,
  `RoleID` int NOT NULL,
  PRIMARY KEY (`UserID`,`RoleID`) USING BTREE,
  KEY `RoleID` (`RoleID`) USING BTREE,
  CONSTRAINT `userroles_ibfk_1` FOREIGN KEY (`UserID`) REFERENCES `users` (`UserID`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `userroles_ibfk_2` FOREIGN KEY (`RoleID`) REFERENCES `roles` (`RoleID`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='用户-角色关联表';

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `UserID` int NOT NULL AUTO_INCREMENT COMMENT '用户唯一标识',
  `PhoneNumber` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '手机号（可用于登录）',
  `Username` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '登录用户名',
  `Email` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '用户邮箱',
  `PasswordHash` char(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'BCrypt加密的密码',
  `DisplayName` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '显示名称',
  `Bio` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '个人简介',
  `AvatarURL` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '头像URL',
  `CreatedAt` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LastLogin` timestamp NULL DEFAULT NULL COMMENT '最后登录时间',
  `IsActive` tinyint(1) DEFAULT '1' COMMENT '账户状态',
  PRIMARY KEY (`UserID`) USING BTREE,
  UNIQUE KEY `Username` (`Username`) USING BTREE,
  UNIQUE KEY `Email` (`Email`) USING BTREE,
  UNIQUE KEY `PhoneNumber` (`PhoneNumber`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='系统用户表';

-- ----------------------------
-- Table structure for verificationcodes
-- ----------------------------
DROP TABLE IF EXISTS `verificationcodes`;
CREATE TABLE `verificationcodes` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `Email` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `Code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `Scene` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'register | change_email',
  `ExpiresAt` timestamp NULL DEFAULT NULL,
  `Used` tinyint(1) NOT NULL DEFAULT '0',
  `UserID` int DEFAULT NULL,
  `CreatedAt` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`) USING BTREE,
  KEY `Email` (`Email`) USING BTREE,
  KEY `Scene` (`Scene`) USING BTREE,
  KEY `ExpiresAt` (`ExpiresAt`) USING BTREE,
  KEY `verificationcodes__email` (`Email`) USING BTREE,
  KEY `verificationcodes__scene` (`Scene`) USING BTREE,
  KEY `verificationcodes__expires_at` (`ExpiresAt`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='邮箱验证码';

-- ----------------------------
-- Local demo seed data moved to seed-local-dev.sql
-- ----------------------------
DROP TRIGGER IF EXISTS `Before_Post_Update`;
delimiter ;;
CREATE TRIGGER `Before_Post_Update` BEFORE UPDATE ON `posts` FOR EACH ROW BEGIN
    IF OLD.Content <> NEW.Content OR OLD.Title <> NEW.Title THEN
        INSERT INTO PostRevisions (
            PostID, UserID, Title, Content, Excerpt, RevisionNotes
        ) VALUES (
            OLD.PostID,
            NEW.UserID,
            OLD.Title,
            OLD.Content,
            OLD.Excerpt,
            '系统自动保存的修订版本'
        );
        SET NEW.CurrentRevisionID = LAST_INSERT_ID();
    END IF;
END
;;
delimiter ;

SET FOREIGN_KEY_CHECKS = 1;
